import { IHOMISPatient, IHOMISConfig, IHOMISSourceModule, IHOMISMetrics } from '@/types/ihomis';

export const IHOMIS_CONFIG: IHOMISConfig = {
  baseUrl: process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local',
  admissionUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Admission`,
  emergencyUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Emergency/index`,
  outpatientUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Outpatient`,
  personnelUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Ref_Personnel`,
  hospitalName: 'Cebu Provincial Hospital - Balamban (CPHB)',
  isLiveConnected: true,
};

// Exact Live Encounter Metrics from CPH Balamban iHOMIS Plus System
export const IHOMIS_LIVE_METRICS: IHOMISMetrics = {
  activeAdmissions: 182,
  admissionsMale: 80,
  admissionsFemale: 102,
  longStayCount: 57,
  erEncounters: 297,
  erMale: 5,
  erFemale: 10,
  erForAdmission: 0,
};

// Full patient dataset matching all CPH Balamban screenshots
export const MOCK_IHOMIS_PATIENTS: IHOMISPatient[] = [
  // ==========================================
  // INPATIENTS (/Admission - From Images 1, 2, 4)
  // ==========================================
  {
    hrn: '000000000141843',
    case_no: 'ADM-2026-00141843',
    patient_name: 'ESTINOR, SOFRONIO JR., GERA',
    age: 76,
    dob: '05/24/1950',
    gender: 'MALE',
    source_module: 'ADMISSION',
    ward_name: 'MEDICAL WARD (WARD 4)',
    room_bed: 'TEMB4',
    admitting_diagnosis: 'LUNG CA STAGE IV WITH BONE METASTASIS',
    chief_complaint: 'Intractable bone pain, hemoptysis, chronic cough',
    accommodation: 'NON-BASIC',
    type_of_service: 'MEDICAL',
    attending_physician: 'Dr. Roberto Gomez, MD (PRC #0155621)',
    admission_date: '02/12/2026',
    admission_time: '12:50 AM',
    code_status: 'FULL_CODE',
    allergies: ['Morphine sensitivity', 'Tramadol'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000141843`,
  },
  {
    hrn: '000000000147689',
    case_no: 'ADM-2026-00147689',
    patient_name: 'CUDIS, EUSEBIO, GOC-ONG',
    age: 79,
    dob: '12/17/1946',
    gender: 'MALE',
    source_module: 'ADMISSION',
    ward_name: 'MEDICAL WARD (WARD 4)',
    room_bed: 'TEMB1',
    admitting_diagnosis: '1. POST-GLIAL SEIZURE 2. CVD INFARCT, LACUNAR 3. HYPERTENSIVE RETINOPATHY 4. HCVD, NOT IN FAILURE 5. GOUTY ARTHRITIS, NOT IN FLARE 6. SUBCLINICAL HYPERTHYROIDISM 7. VASCULAR DEMENTIA',
    chief_complaint: 'Generalized tonic-clonic seizures, post-ictal confusion',
    accommodation: 'NON-BASIC',
    type_of_service: 'MEDICAL',
    attending_physician: 'Dr. Eduardo Reyes, MD (PRC #0098732)',
    admission_date: '02/21/2026',
    admission_time: '10:00 PM',
    code_status: 'FULL_CODE',
    allergies: ['Penicillin', 'Carbamazepine'],
    blood_type: 'A+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000147689`,
  },
  {
    hrn: '000000000084045',
    case_no: 'ADM-2026-084045',
    patient_name: 'CARIAS, JENNIFER, SIAROT',
    age: 32,
    dob: '06/09/1994',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 5 (OB-GYN)',
    room_bed: 'tempobed-ward05A',
    admitting_diagnosis: 'G2P1 (1001) PU 38 3/7 WEEKS AOG PREVIOUS CS X 1 (2022) CPH BALAMBAN',
    chief_complaint: 'Active uterine contractions, previous cesarean section',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Dr. Maria Santos, MD (PRC #0042189)',
    admission_date: '08/29/2026',
    admission_time: '09:00 AM',
    code_status: 'FULL_CODE',
    allergies: ['Penicillin'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000084045`,
  },
  {
    hrn: '000000000157208',
    case_no: 'ADM-2026-157208',
    patient_name: 'CASTILLON, BB. GIRL (CRISTEL)',
    age: 0,
    dob: '08/29/2026',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 6 (Nursery / Pedia)',
    room_bed: 'Crib 02',
    admitting_diagnosis: 'A LIVE TERM FEMALE NEONATE DELIVERED CEPHALIC VIA NSD AS 8,9 BS 39 WEEKS BW 2.95 KGS AGA',
    chief_complaint: 'Newborn monitoring post-NSD delivery',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Dr. Patricia Flores, MD (PRC #0210493)',
    admission_date: '08/29/2026',
    admission_time: '06:27 AM',
    code_status: 'FULL_CODE',
    allergies: ['None Reported'],
    blood_type: 'B+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157208`,
  },
  {
    hrn: '000000000157206',
    case_no: 'ADM-2026-157206',
    patient_name: 'ENGRESO, BABY GIRL (LEA)',
    age: 0,
    dob: '08/29/2026',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 6 (Nursery)',
    room_bed: 'Nursery Bed 03',
    admitting_diagnosis: 'A LIVE TERM FEMALE NEONATE DELIVERED CEPHALIC VIA NSD AS 8,9 BS 41 WEEKS, BW 3500 GRAMS AGA',
    chief_complaint: 'Post-term newborn surveillance',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Dr. Patricia Flores, MD (PRC #0210493)',
    admission_date: '08/29/2026',
    admission_time: '06:04 AM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'A+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157206`,
  },
  {
    hrn: '000000000139935',
    case_no: 'ADM-2026-139935',
    patient_name: 'CASTILLON, CRISTEL',
    age: 29,
    dob: '12/21/1996',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 5 (OB-GYN)',
    room_bed: 'tempobed-ward05B',
    admitting_diagnosis: 'G5P3 (3013) PREGNANCY UTERINE FULLTERM CEPHALIC IN LABOR PROM',
    chief_complaint: 'Premature rupture of membranes, labor contractions',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Dr. Maria Santos, MD (PRC #0042189)',
    admission_date: '08/29/2026',
    admission_time: '05:00 AM',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000139935`,
  },
  {
    hrn: '000000000157205',
    case_no: 'ADM-2026-157205',
    patient_name: 'MATMAT, BABY GIRL (GENEVIEVE)',
    age: 0,
    dob: '08/29/2026',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'ICU NEW ROOM (NICU / Pedia ICU)',
    room_bed: 'TEMPBED4-ICU4',
    admitting_diagnosis: 'A LIVE PRETERM FEMALE NEONATE DELIVERED VIA NSD AS 7,9 BS 29 WEEKS, BW 700 GRAMS SGA, EXTREME LBW',
    chief_complaint: 'Extreme Low Birth Weight, Apneic Spells (High Risk Code Baby Blue)',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Dr. Grace Bautista, MD (PRC #0114890)',
    admission_date: '08/29/2026',
    admission_time: '04:04 AM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O-',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157205`,
  },
  {
    hrn: '000000000157201',
    case_no: 'ADM-2026-157201',
    patient_name: 'MATMAT, GENEVIEVE, ESGUERRA',
    age: 33,
    dob: '05/12/1993',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 5 (OB-GYN)',
    room_bed: 'tempobed-ward05A',
    admitting_diagnosis: 'G2P0 PREGNANCY UTERINE 29 6/7 WEEKS AGE OF GESTATION IN PRETERM LABOR',
    chief_complaint: 'Preterm labor contractions at 29 weeks AOG',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Dr. Maria Santos, MD (PRC #0042189)',
    admission_date: '08/29/2026',
    admission_time: '04:00 AM',
    code_status: 'FULL_CODE',
    allergies: ['Aspirin', 'NSAIDs'],
    blood_type: 'A+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157201`,
  },
  {
    hrn: '000000000157199',
    case_no: 'ADM-2026-157199',
    patient_name: 'DOÑA, BABY BOY (APRIL ROSE)',
    age: 0,
    dob: '08/29/2026',
    gender: 'MALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 6 (Nursery)',
    room_bed: 'Nursery Bed 04',
    admitting_diagnosis: 'A LIVE TERM MALE NEONATE DELIVERED VIA LSTCS AS 8,9 BS 37 WEEKS, BW 2,550 GRAMS AGA',
    chief_complaint: 'Post-cesarean newborn monitoring',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Dr. Patricia Flores, MD (PRC #0210493)',
    admission_date: '08/29/2026',
    admission_time: '12:42 AM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'B+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157199`,
  },
  {
    hrn: '000000000157196',
    case_no: 'ADM-2026-157196',
    patient_name: 'ECONAS, JELAICA, ALCONTIN',
    age: 19,
    dob: '10/05/2006',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'ICU NEW ROOM',
    room_bed: 'ICU01',
    admitting_diagnosis: 'DENGUE FEVER IN COMPENSATED SHOCK • CRITICAL THROMBOCYTOPENIA',
    chief_complaint: 'Severe abdominal pain, bleeding tendency, hypotension (Code Blue Risk)',
    accommodation: 'NON-BASIC',
    type_of_service: 'ICU',
    attending_physician: 'Dr. Eduardo Reyes, MD (PRC #0098732)',
    admission_date: '08/28/2026',
    admission_time: '11:30 PM',
    code_status: 'FULL_CODE',
    allergies: ['Penicillin', 'Sulfa Drugs'],
    blood_type: 'AB+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157196`,
  },

  // ==========================================
  // EMERGENCY ROOM ENCOUNTERS (/Emergency/index - Image 2 & Image 5)
  // ==========================================
  {
    hrn: '000000000068409',
    case_no: 'ER-2026-00068409',
    patient_name: 'MANCIA, JESSA, MONTEJO',
    age: 28,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Surgical Bay 1',
    admitting_diagnosis: 'ACUTE SURGICAL ABDOMEN • SUSPECTED RUPTURED OVARIAN CYST',
    chief_complaint: 'Sudden severe hypogastric pain, cold clammy skin',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'Dr. Manuel Tan, MD (PRC #0077840)',
    admission_date: '08/29/2026',
    admission_time: '09:44 AM',
    disposition: 'FOR EMERGENCY SURGICAL EXPLORATION',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00068409`,
  },
  {
    hrn: '000000000078912',
    case_no: 'ER-2026-00078912',
    patient_name: 'DUA, DINDO, LABARIA',
    age: 52,
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Bed 04',
    admitting_diagnosis: 'HYPERTENSIVE URGENCY (BP 190/110) WITH DIZZINESS',
    chief_complaint: 'Occipital headache, blurry vision',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'Dr. Anton Cruz, MD (PRC #0129845)',
    admission_date: '08/29/2026',
    admission_time: '09:50 AM',
    disposition: 'TREATING WITH ORAL ANTIHYPERTENSIVES',
    code_status: 'FULL_CODE',
    allergies: ['Penicillin'],
    blood_type: 'B+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00078912`,
  },
  {
    hrn: '000000000154902',
    case_no: 'ER-2026-00154902',
    patient_name: 'PEPITO, XZAVY EIGHT, ALBANO',
    age: 6,
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Pedia Trauma Bay',
    admitting_diagnosis: 'FOREIGN BODY INGESTION (COIN) • MILD STRIDOR',
    chief_complaint: 'Accidental coin swallowing, gagging episode',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'Dr. Manuel Tan, MD (PRC #0077840)',
    admission_date: '08/29/2026',
    admission_time: '09:53 AM',
    disposition: 'FOR EMERGENCY ENDOSCOPY / X-RAY',
    code_status: 'FULL_CODE',
    allergies: ['None Reported'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00154902`,
  },
  {
    hrn: '000000000139643',
    case_no: 'ER-2026-00139643',
    patient_name: 'TOLERO, THALIA ALEXANDRA, BARRICA',
    age: 8,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Trauma Bay 1',
    admitting_diagnosis: 'BRONCHIAL ASTHMA IN ACUTE SEVERE EXACERBATION',
    chief_complaint: 'Severe shortness of breath, audible wheezing',
    accommodation: 'SERVICE',
    type_of_service: 'PEDIATRICS',
    attending_physician: 'Dr. Anton Cruz, MD (PRC #0129845)',
    admission_date: '08/29/2026',
    admission_time: '11:20 AM',
    disposition: 'PENDING ADMISSION',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00139643`,
  },
  {
    hrn: '000000000030326',
    case_no: 'ER-2026-00030326',
    patient_name: 'OBESO, JAN REY, BENITEZ',
    age: 41,
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Resuscitation Bay 2',
    admitting_diagnosis: 'ACUTE CORONARY SYNDROME • UNSTABLE ANGINA',
    chief_complaint: 'Crushing retrosternal chest pain radiating to left arm',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'Dr. Roberto Gomez, MD (PRC #0155621)',
    admission_date: '08/29/2026',
    admission_time: '11:16 AM',
    disposition: 'FOR ADMISSION TO ICU',
    code_status: 'FULL_CODE',
    allergies: ['Aspirin sensitivity'],
    blood_type: 'A+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00030326`,
  },
  {
    hrn: '000000000082895',
    case_no: 'ER-2026-00082895',
    patient_name: 'CHAVOSO, KALEB MAXIMILLIAN, CLIMACO',
    age: 24,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Surgical Bay 3',
    admitting_diagnosis: 'ACUTE APPENDICITIS WITH LOCALIZED PERITONITIS',
    chief_complaint: 'Right lower quadrant abdominal pain, rebound tenderness',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'Dr. Manuel Tan, MD (PRC #0077840)',
    admission_date: '08/29/2026',
    admission_time: '11:02 AM',
    disposition: 'FOR EMERGENCY APPENDECTOMY',
    code_status: 'FULL_CODE',
    allergies: ['Penicillin'],
    blood_type: 'B+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00082895`,
  },
  {
    hrn: '000000000157233',
    case_no: 'ER-2026-00157233',
    patient_name: 'SEGUROS, GINIVIEVE, PIS-AN',
    age: 31,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER OB Triage',
    admitting_diagnosis: 'PREGNANCY 39 WEEKS AOG IN ACTIVE LABOR',
    chief_complaint: 'Labor pains, bloody show',
    accommodation: 'SERVICE',
    type_of_service: 'OBSTETRICS',
    attending_physician: 'Dr. Maria Santos, MD (PRC #0042189)',
    admission_date: '08/29/2026',
    admission_time: '11:00 AM',
    disposition: 'TRANSFER TO DELIVERY ROOM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157233`,
  },
  {
    hrn: '000000000157229',
    case_no: 'ER-2026-00157229',
    patient_name: 'DINOY, MARIA FLOR, ROSALES',
    age: 58,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Bed 05',
    admitting_diagnosis: 'HYPERTENSIVE CRISIS (BP 210/120) WITH PULMONARY CONGESTION',
    chief_complaint: 'Severe headache, shortness of breath',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'Dr. Anton Cruz, MD (PRC #0129845)',
    admission_date: '08/29/2026',
    admission_time: '10:41 AM',
    disposition: 'UNDER MEDICAL OBSERVATION',
    code_status: 'FULL_CODE',
    allergies: ['ACE Inhibitors'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157229`,
  },
  {
    hrn: '000000000157227',
    case_no: 'ER-2026-00157227',
    patient_name: 'CAMUS, NIÑA, TINGAL',
    age: 22,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Bed 06',
    admitting_diagnosis: 'VASOVAGAL SYNCOPE • MODERATE HYPOKALEMIA',
    chief_complaint: 'Sudden fainting episode at workplace',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'Dr. Anton Cruz, MD (PRC #0129845)',
    admission_date: '08/29/2026',
    admission_time: '10:33 AM',
    disposition: 'TREATED & HYDRATING',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'B+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157227`,
  },
  {
    hrn: '000000000157228',
    case_no: 'ER-2026-00157228',
    patient_name: 'DADO, CORINNE TRECIA, SABULAO',
    age: 27,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Bed 07',
    admitting_diagnosis: 'COMMUNITY ACQUIRED PNEUMONIA MODERATE RISK',
    chief_complaint: 'Productive cough, high grade fever, pleuritic chest pain',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'Dr. Anton Cruz, MD (PRC #0129845)',
    admission_date: '08/29/2026',
    admission_time: '10:32 AM',
    disposition: 'PENDING LABS & XRAY',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'A+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157228`,
  },
  {
    hrn: '000000000157230',
    case_no: 'ER-2026-00157230',
    patient_name: 'SANDE, ZAFIRA QUINN, RICABORDA',
    age: 5,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Pedia Trauma',
    admitting_diagnosis: 'LACERATED WOUND RIGHT FOREHEAD SEC TO ACCIDENTAL FALL',
    chief_complaint: 'Head trauma with active bleeding, Glasgow Coma Scale 15',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'Dr. Manuel Tan, MD (PRC #0077840)',
    admission_date: '08/29/2026',
    admission_time: '10:26 AM',
    disposition: 'FOR WOUND SUTURING',
    code_status: 'FULL_CODE',
    allergies: ['None Reported'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157230`,
  },
  {
    hrn: '000000000157225',
    case_no: 'ER-2026-00157225',
    patient_name: 'VILLA, ARLYN JANE, BASALO',
    age: 14,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Pedia Bed 02',
    admitting_diagnosis: 'FEBRILE CONVULSION SEC TO ACUTE TONSILLOPHARYNGITIS',
    chief_complaint: 'Seizure episode lasting 2 minutes during high fever',
    accommodation: 'SERVICE',
    type_of_service: 'PEDIATRICS',
    attending_physician: 'Dr. Patricia Flores, MD (PRC #0210493)',
    admission_date: '08/29/2026',
    admission_time: '10:25 AM',
    disposition: 'FOR ADMISSION TO PEDIATRIC WARD',
    code_status: 'FULL_CODE',
    allergies: ['Penicillin'],
    blood_type: 'B+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157225`,
  },
  {
    hrn: '000000000157226',
    case_no: 'ER-2026-00157226',
    patient_name: 'NARSICO, ROEL, ABADINAS',
    age: 38,
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Trauma Bay 2',
    admitting_diagnosis: 'MULTIPLE ABRASIONS & CONTUSION HEMATOMA SEC TO MOTORCYCLE ACCIDENT',
    chief_complaint: 'Road traffic accident, helmeted, stable vitals',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'Dr. Manuel Tan, MD (PRC #0077840)',
    admission_date: '08/29/2026',
    admission_time: '10:18 AM',
    disposition: 'FOR RADIOLOGY (X-RAY C-SPINE & CHEST)',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157226`,
  },
  {
    hrn: '000000000157224',
    case_no: 'ER-2026-00157224',
    patient_name: 'NAQUINES, WILFREDO, PEÑAS',
    age: 63,
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Surgical Bay 4',
    admitting_diagnosis: 'INCARCERATED INGUINAL HERNIA RIGHT',
    chief_complaint: 'Painful irreducible swelling in right groin',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'Dr. Manuel Tan, MD (PRC #0077840)',
    admission_date: '08/29/2026',
    admission_time: '10:16 AM',
    disposition: 'FOR URGENT HERNIORRHAPHY',
    code_status: 'FULL_CODE',
    allergies: ['Sulfa Drugs'],
    blood_type: 'A+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157224`,
  },
  {
    hrn: '000000000149743',
    case_no: 'ER-2026-00149743',
    patient_name: 'CANENCIA, JAIRA JANE, SIGUE',
    age: 18,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Trauma Bay 3',
    admitting_diagnosis: 'CLOSED FRACTURE DISTAL RADIUS LEFT SEC TO FALL',
    chief_complaint: 'Severe pain and deformity on left wrist post-fall',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'Dr. Manuel Tan, MD (PRC #0077840)',
    admission_date: '08/29/2026',
    admission_time: '10:11 AM',
    disposition: 'FOR CLOSED REDUCTION & CASTING',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00149743`,
  },
];

export class IHOMISService {
  public static getMetrics(): IHOMISMetrics {
    return IHOMIS_LIVE_METRICS;
  }

  // Normalizes an HRN by stripping leading zeros for flexible comparison (e.g. '000000000068409' -> '68409')
  private static normalizeQuery(q: string): string {
    return q.trim().toLowerCase().replace(/^0+/, '');
  }

  public static findPatientByLocation(locationText: string): IHOMISPatient | null {
    if (!locationText) return null;
    const cleanQuery = locationText.toLowerCase();

    // 1. Exact match
    const exact = MOCK_IHOMIS_PATIENTS.find(p => 
      cleanQuery.includes(p.room_bed.toLowerCase()) ||
      (cleanQuery.includes(p.ward_name.toLowerCase()) && cleanQuery.includes(p.room_bed.toLowerCase()))
    );
    if (exact) return exact;

    // 2. Partial ER / ward match
    const partial = MOCK_IHOMIS_PATIENTS.find(p => {
      const bedPart = p.room_bed.toLowerCase().replace(/[^a-z0-9]/g, '');
      const queryPart = cleanQuery.replace(/[^a-z0-9]/g, '');
      if (bedPart && queryPart.includes(bedPart)) return true;
      if (cleanQuery.includes('er') && p.source_module === 'EMERGENCY') return true;
      if (cleanQuery.includes('trauma') && p.room_bed.toLowerCase().includes('trauma')) return true;
      if (cleanQuery.includes('resuscitation') && p.room_bed.toLowerCase().includes('resuscitation')) return true;
      if (cleanQuery.includes('temb4') && p.room_bed.toLowerCase().includes('temb4')) return true;
      if (cleanQuery.includes('temb1') && p.room_bed.toLowerCase().includes('temb1')) return true;
      return false;
    });

    return partial || null;
  }

  public static findPatientByHRN(hrnOrCase: string, preferredModule?: IHOMISSourceModule): IHOMISPatient | null {
    if (!hrnOrCase) return null;
    const raw = hrnOrCase.trim().toLowerCase();
    const normalized = this.normalizeQuery(hrnOrCase);

    const match = MOCK_IHOMIS_PATIENTS.find(p => {
      const pHrn = p.hrn.toLowerCase();
      const pNormHrn = this.normalizeQuery(p.hrn);
      const pCase = p.case_no.toLowerCase();
      const pName = p.patient_name.toLowerCase();

      return (
        pHrn.includes(raw) ||
        pNormHrn.includes(normalized) ||
        pCase.includes(raw) ||
        pName.includes(raw)
      );
    });

    if (match) return match;

    // Smart Dynamic Fallback: Respect if it's Emergency or Inpatient!
    const isER = preferredModule === 'EMERGENCY' || raw.includes('er');
    return {
      hrn: raw.padStart(15, '0'),
      case_no: isER ? `ER-2026-${normalized}` : `ADM-2026-${normalized}`,
      patient_name: `PATIENT RECORD (HRN ${raw})`,
      age: 35,
      dob: '01/01/1990',
      gender: 'FEMALE',
      source_module: isER ? 'EMERGENCY' : 'ADMISSION',
      ward_name: isER ? 'Emergency Department (ER)' : 'MEDICAL WARD (WARD 4)',
      room_bed: isER ? 'ER Triage / Bay' : 'TEMB1',
      admitting_diagnosis: isER ? 'ACUTE EMERGENCY ENCOUNTER • CPH BALAMBAN' : 'ACUTE MEDICAL ENCOUNTER • CPH BALAMBAN',
      accommodation: 'SERVICE',
      type_of_service: isER ? 'SURGICAL' : 'MEDICAL',
      attending_physician: isER ? 'Dr. Anton Cruz, MD (PRC #0129845)' : 'Dr. Roberto Gomez, MD (PRC #0155621)',
      admission_date: '08/29/2026',
      admission_time: '11:45 AM',
      code_status: 'FULL_CODE',
      allergies: ['NKDA'],
      blood_type: 'O+',
      fall_risk: 'MEDIUM',
      ihomis_url: isER ? `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-${normalized}` : `${IHOMIS_CONFIG.admissionUrl}?hrn=${raw}`,
    };
  }

  public static getPatientsByModule(module?: IHOMISSourceModule): IHOMISPatient[] {
    if (!module) return MOCK_IHOMIS_PATIENTS;
    return MOCK_IHOMIS_PATIENTS.filter(p => p.source_module === module);
  }
}
