import { IHOMISPatient, IHOMISConfig, IHOMISSourceModule, IHOMISMetrics } from '@/types/ihomis';

export const IHOMIS_CONFIG: IHOMISConfig = {
  baseUrl: process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local',
  admissionUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Admission`,
  emergencyUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Emergency/index`,
  outpatientUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Outpatient`,
  personnelUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Ref_Personnel`,
  hospitalName: 'Cebu Provincial Hospital - Balamban (CPHB)',
  isLiveConnected: true,
};

// Exact Live Encounter Metrics from CPH Balamban iHOMIS Plus System (Latest Live Sync)
export const IHOMIS_LIVE_METRICS: IHOMISMetrics = {
  activeAdmissions: 181,
  admissionsMale: 78,
  admissionsFemale: 103,
  longStayCount: 57,
  erEncounters: 299,
  erMale: 4,
  erFemale: 11,
  erForAdmission: 0,
};

// Full patient dataset matching all CPH Balamban screenshots
export const MOCK_IHOMIS_PATIENTS: IHOMISPatient[] = [
  // ==========================================
  // INPATIENTS (/Admission - From Live System)
  // ==========================================
  {
    hrn: '000000000157233',
    case_no: 'ADM-2026-157233',
    patient_name: 'SEGUROS, GINIVIEVE, PIS-AN',
    age: 31,
    dob: '11/01/1995',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 5 (OB-GYN)',
    room_bed: 'tempobed-ward05A',
    admitting_diagnosis: 'G2P1 (1001) PU 38 5/7 WEEKS AOG CEPHALIC IN LABOR',
    chief_complaint: 'Labor contractions, active stage',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBPRDOC',
    attending_physician: 'OB-GYN Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '11:30 AM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157233`,
  },
  {
    hrn: '000000000157210',
    case_no: 'ADM-2026-157210',
    patient_name: 'LEGASPINO, EDELYN, CABRAS',
    age: 27,
    dob: '11/19/1998',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 5 (OB-GYN)',
    room_bed: 'tempobed-ward05B',
    admitting_diagnosis: 'G1P0 PREGNANCY UTERINE FULLTERM CEPHALIC IN LABOR',
    chief_complaint: 'First pregnancy full-term active labor',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBPRDOC',
    attending_physician: 'OB-GYN Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '11:00 AM',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'B+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157210`,
  },
  {
    hrn: '000000000141843',
    case_no: 'ADM-2026-00141843',
    patient_name: 'ESTINOR, SOFRONIO JR., GERA',
    age: 76,
    dob: '05/24/1950',
    gender: 'MALE',
    source_module: 'ADMISSION',
    ward_name: 'MEDICAL WARD (WARD 4)',
    room_bed: 'TEMB4',
    admitting_diagnosis: 'LUNG CA STAGE IV WITH BONE METASTASIS',
    chief_complaint: 'Intractable bone pain, hemoptysis, chronic cough',
    accommodation: 'NON-BASIC',
    type_of_service: 'MEDICAL',
    attending_physician: 'Internal Medicine Attending',
    admission_date: '02/12/2026',
    admission_time: '12:50 AM',
    code_status: 'FULL_CODE',
    allergies: ['Morphine sensitivity', 'Tramadol'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000141843`,
  },
  {
    hrn: '000000000147689',
    case_no: 'ADM-2026-00147689',
    patient_name: 'CUDIS, EUSEBIO, GOC-ONG',
    age: 79,
    dob: '12/17/1946',
    gender: 'MALE',
    source_module: 'ADMISSION',
    ward_name: 'MEDICAL WARD (WARD 4)',
    room_bed: 'TEMB1',
    admitting_diagnosis: '1. POST-GLIAL SEIZURE 2. CVD INFARCT, LACUNAR 3. HYPERTENSIVE RETINOPATHY 4. HCVD, NOT IN FAILURE 5. GOUTY ARTHRITIS, NOT IN FLARE 6. SUBCLINICAL HYPERTHYROIDISM 7. VASCULAR DEMENTIA',
    chief_complaint: 'Generalized tonic-clonic seizures, post-ictal confusion',
    accommodation: 'NON-BASIC',
    type_of_service: 'MEDICAL',
    attending_physician: 'Cardiology Attending Physician',
    admission_date: '02/21/2026',
    admission_time: '10:00 PM',
    code_status: 'FULL_CODE',
    allergies: ['Penicillin', 'Carbamazepine'],
    blood_type: 'A+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000147689`,
  },
  {
    hrn: '000000000084045',
    case_no: 'ADM-2026-084045',
    patient_name: 'CARIAS, JENNIFER, SIAROT',
    age: 32,
    dob: '06/09/1994',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 5 (OB-GYN)',
    room_bed: 'tempobed-ward05A',
    admitting_diagnosis: 'G2P1 (1001) PU 38 3/7 WEEKS AOG PREVIOUS CS X 1 (2022) CPH BALAMBAN',
    chief_complaint: 'Active uterine contractions, previous cesarean section',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'OB-GYN Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '09:00 AM',
    code_status: 'FULL_CODE',
    allergies: ['Penicillin'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000084045`,
  },
  {
    hrn: '000000000157208',
    case_no: 'ADM-2026-157208',
    patient_name: 'CASTILLON, BB. GIRL (CRISTEL)',
    age: 0,
    dob: '08/29/2026',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 6 (Nursery / Pedia)',
    room_bed: 'Crib 02',
    admitting_diagnosis: 'A LIVE TERM FEMALE NEONATE DELIVERED CEPHALIC VIA NSD AS 8,9 BS 39 WEEKS BW 2.95 KGS AGA',
    chief_complaint: 'Newborn monitoring post-NSD delivery',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Pediatric Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '06:27 AM',
    code_status: 'FULL_CODE',
    allergies: ['None Reported'],
    blood_type: 'B+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157208`,
  },
  {
    hrn: '000000000157206',
    case_no: 'ADM-2026-157206',
    patient_name: 'ENGRESO, BABY GIRL (LEA)',
    age: 0,
    dob: '08/29/2026',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 6 (Nursery)',
    room_bed: 'Nursery Bed 03',
    admitting_diagnosis: 'A LIVE TERM FEMALE NEONATE DELIVERED CEPHALIC VIA NSD AS 8,9 BS 41 WEEKS, BW 3500 GRAMS AGA',
    chief_complaint: 'Post-term newborn surveillance',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Pediatric Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '06:04 AM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'A+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157206`,
  },
  {
    hrn: '000000000139935',
    case_no: 'ADM-2026-139935',
    patient_name: 'CASTILLON, CRISTEL',
    age: 29,
    dob: '12/21/1996',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 5 (OB-GYN)',
    room_bed: 'tempobed-ward05B',
    admitting_diagnosis: 'G5P3 (3013) PREGNANCY UTERINE FULLTERM CEPHALIC IN LABOR PROM',
    chief_complaint: 'Premature rupture of membranes, labor contractions',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'OB-GYN Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '05:00 AM',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000139935`,
  },
  {
    hrn: '000000000157205',
    case_no: 'ADM-2026-157205',
    patient_name: 'MATMAT, BABY GIRL (GENEVIEVE)',
    age: 0,
    dob: '08/29/2026',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'ICU NEW ROOM (NICU / Pedia ICU)',
    room_bed: 'TEMPBED4-ICU4',
    admitting_diagnosis: 'A LIVE PRETERM FEMALE NEONATE DELIVERED VIA NSD AS 7,9 BS 29 WEEKS, BW 700 GRAMS SGA, EXTREME LBW',
    chief_complaint: 'Extreme Low Birth Weight, Apneic Spells (High Risk Code Baby Blue)',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Neonatology Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '04:04 AM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O-',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157205`,
  },

  // ==========================================
  // EMERGENCY ROOM ENCOUNTERS (/Emergency - From Latest Screenshot)
  // ==========================================
  {
    hrn: '000000000157235',
    case_no: 'ER-2026-00157235',
    patient_name: 'AROG, CHARNIE, SIAROT',
    age: 26,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Bed 01',
    admitting_diagnosis: 'ACUTE GASTROENTERITIS WITH MODERATE DEHYDRATION',
    chief_complaint: 'Frequent watery stools, vomiting, dizziness',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'ER Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '12:19 PM',
    disposition: 'FOR HYDRATION & OBSERVATION',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157235`,
  },
  {
    hrn: '000000000025909',
    case_no: 'ER-2026-00025909',
    patient_name: 'NIEZ, MELANIE, CUESTA',
    age: 30,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER OB Triage Bay',
    admitting_diagnosis: 'PREGNANCY 38 WEEKS AOG IN EARLY LABOR • CEPHALIC',
    chief_complaint: 'Mild uterine contractions, bloody show',
    accommodation: 'SERVICE',
    type_of_service: 'OBSTETRICS',
    attending_physician: 'ER Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '11:59 AM',
    disposition: 'TRANSFER TO WARD 5 / DELIVERY ROOM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'A+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00025909`,
  },
  {
    hrn: '000000000107451',
    case_no: 'ER-2026-00107451',
    patient_name: 'DURAN, JAMES KHIAN, CAPULE',
    age: 12,
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Trauma Bay 1',
    admitting_diagnosis: 'LACERATED WOUND RIGHT FOREARM SEC TO SHARP OBJECT INJURY',
    chief_complaint: 'Deep laceration on forearm with active bleeding',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'ER Surgeon On-Duty',
    admission_date: '08/29/2026',
    admission_time: '11:56 AM',
    disposition: 'FOR EXPLORATION & SUTURE REPAIR',
    code_status: 'FULL_CODE',
    allergies: ['None Reported'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00107451`,
  },
  {
    hrn: '000000000057010',
    case_no: 'ER-2026-00057010',
    patient_name: 'CASAJURAS, BEA ZHAVIA, PAUL',
    age: 4,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Pedia Trauma Bay',
    admitting_diagnosis: 'FEBRILE SEIZURE SECONDARY TO ACUTE UPPER RESPIRATORY INFECTION',
    chief_complaint: 'Seizure lasting 1 minute with T 39.5°C',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'Pediatric ER Attending',
    admission_date: '08/29/2026',
    admission_time: '11:48 AM',
    disposition: 'FOR ADMISSION TO PEDIATRICS',
    code_status: 'FULL_CODE',
    allergies: ['Penicillin'],
    blood_type: 'B+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00057010`,
  },
  {
    hrn: '000000000068409',
    case_no: 'ER-2026-00068409',
    patient_name: 'MANCIA, JESSA, MONTEJO',
    age: 28,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Surgical Bay 1',
    admitting_diagnosis: 'ACUTE SURGICAL ABDOMEN • SUSPECTED RUPTURED OVARIAN CYST',
    chief_complaint: 'Sudden severe hypogastric pain, cold clammy skin',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'Surgical Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '09:44 AM',
    disposition: 'FOR EMERGENCY SURGICAL EXPLORATION',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00068409`,
  },
  {
    hrn: '000000000088192',
    case_no: 'ER-2026-00088192',
    patient_name: 'ALVAREZ, RODOLFO, ALFONSO',
    age: 58,
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Acute Resus Bay 2',
    admitting_diagnosis: 'HYPERTENSIVE CRISIS / IMPENDING ACUTE CORONARY SYNDROME',
    chief_complaint: 'Crushing retrosternal chest pain radiating to left jaw, BP 210/120',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'Internal Medicine / Cardiology On-Duty',
    admission_date: '08/29/2026',
    admission_time: '09:15 AM',
    disposition: 'FOR IMMEDIATE ECG, TROPONIN & ICU ADMISSION',
    code_status: 'FULL_CODE',
    allergies: ['Aspirin'],
    blood_type: 'B+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00088192`,
  },
  {
    hrn: '000000000094182',
    case_no: 'ER-2026-00094182',
    patient_name: 'VILLAMOR, REYNALDO, GOMEZ',
    age: 45,
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Trauma Bay 3',
    admitting_diagnosis: 'MULTIPLE TRAUMA SEC TO VEHICULAR ACCIDENT (MC vs TRUCK)',
    chief_complaint: 'Severe head contusion, closed fracture right femur',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'Trauma Team / Orthopedics',
    admission_date: '08/29/2026',
    admission_time: '08:45 AM',
    disposition: 'FOR STAT CT-SCAN & EMERGENCY OR EXPLORATION',
    code_status: 'FULL_CODE',
    allergies: ['None Reported'],
    blood_type: 'A+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00094182`,
  },
  {
    hrn: '000000000101948',
    case_no: 'ER-2026-00101948',
    patient_name: 'CABARRUBIAS, MARY ROSE, TULOD',
    age: 22,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER OB Triage Bay 2',
    admitting_diagnosis: 'ECTOPIC PREGNANCY RUPTURED WITH HYPOVOLEMIC SHOCK',
    chief_complaint: 'Severe RLQ pain, profuse bleeding, syncope',
    accommodation: 'SERVICE',
    type_of_service: 'OBSTETRICS',
    attending_physician: 'OB-GYN Specialist On-Call',
    admission_date: '08/29/2026',
    admission_time: '08:20 AM',
    disposition: 'STAT OR / BLOOD TRANSFUSION',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O-',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00101948`,
  },
  {
    hrn: '000000000115029',
    case_no: 'ER-2026-00115029',
    patient_name: 'DELA TORRE, EMMANUEL, BONTILAO',
    age: 63,
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Isolation Bay',
    admitting_diagnosis: 'COMMUNITY ACQUIRED PNEUMONIA • HIGH RISK • ACUTE RESPIRATORY FAILURE',
    chief_complaint: 'Severe dyspnea, SPO2 82% on room air, high grade fever',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'Pulmonology / Internal Medicine',
    admission_date: '08/29/2026',
    admission_time: '07:55 AM',
    disposition: 'FOR INTUBATION / MECHANICAL VENTILATION',
    code_status: 'FULL_CODE',
    allergies: ['Penicillin'],
    blood_type: 'B+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00115029`,
  },
  {
    hrn: '000000000122849',
    case_no: 'ER-2026-00122849',
    patient_name: 'MONTEFALCON, DANILO, PAQUIBOT',
    age: 36,
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Observation Bed 04',
    admitting_diagnosis: 'ACUTE APPENDICITIS IN EVOLUTION',
    chief_complaint: 'Migratory periumbilical to right iliac fossa pain, nausea',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'General Surgery Attending',
    admission_date: '08/29/2026',
    admission_time: '07:30 AM',
    disposition: 'FOR EMERGENCY APPENDECTOMY',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00122849`,
  },
  {
    hrn: '000000000130948',
    case_no: 'ER-2026-00130948',
    patient_name: 'QUIJANO, PRINCESS NICOLE, ARAGON',
    age: 8,
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Pedia Observation 2',
    admitting_diagnosis: 'DENGUE WITH WARNING SIGNS (ABDOMINAL PAIN, PERSISTENT VOMITING)',
    chief_complaint: '4 days high fever, rash, epistaxis',
    accommodation: 'SERVICE',
    type_of_service: 'PEDIATRICS',
    attending_physician: 'Pediatric Specialist',
    admission_date: '08/29/2026',
    admission_time: '06:40 AM',
    disposition: 'FOR SERIAL CBC, PLATELET MONITORING & ADMISSION',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'A+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00130948`,
  },
];

export class IHOMISService {
  public static getMetrics(): IHOMISMetrics {
    return IHOMIS_LIVE_METRICS;
  }

  private static normalizeQuery(q: string): string {
    return q.trim().toLowerCase().replace(/^0+/, '');
  }

  public static findPatientByLocation(locationText: string): IHOMISPatient | null {
    if (!locationText) return null;
    const cleanQuery = locationText.toLowerCase();

    const exact = MOCK_IHOMIS_PATIENTS.find(p => 
      cleanQuery.includes(p.room_bed.toLowerCase()) ||
      (cleanQuery.includes(p.ward_name.toLowerCase()) && cleanQuery.includes(p.room_bed.toLowerCase()))
    );
    if (exact) return exact;

    const partial = MOCK_IHOMIS_PATIENTS.find(p => {
      const bedPart = p.room_bed.toLowerCase().replace(/[^a-z0-9]/g, '');
      const queryPart = cleanQuery.replace(/[^a-z0-9]/g, '');
      if (bedPart && queryPart.includes(bedPart)) return true;
      if (cleanQuery.includes('er') && p.source_module === 'EMERGENCY') return true;
      if (cleanQuery.includes('temb4') && p.room_bed.toLowerCase().includes('temb4')) return true;
      if (cleanQuery.includes('temb1') && p.room_bed.toLowerCase().includes('temb1')) return true;
      return false;
    });

    return partial || null;
  }

  public static findPatientByHRN(hrnOrCase: string, preferredModule?: IHOMISSourceModule): IHOMISPatient | null {
    if (!hrnOrCase) return null;
    const raw = hrnOrCase.trim().toLowerCase();
    const normalized = this.normalizeQuery(hrnOrCase);

    const match = MOCK_IHOMIS_PATIENTS.find(p => {
      const pHrn = p.hrn.toLowerCase();
      const pNormHrn = this.normalizeQuery(p.hrn);
      const pCase = p.case_no.toLowerCase();
      const pName = p.patient_name.toLowerCase();

      return (
        pHrn.includes(raw) ||
        pNormHrn.includes(normalized) ||
        pCase.includes(raw) ||
        pName.includes(raw)
      );
    });

    if (match) return match;

    const isER = preferredModule === 'EMERGENCY' || raw.includes('er');
    return {
      hrn: raw.padStart(15, '0'),
      case_no: isER ? `ER-2026-${normalized}` : `ADM-2026-${normalized}`,
      patient_name: `PATIENT RECORD (HRN ${raw})`,
      age: 35,
      dob: '01/01/1990',
      gender: 'FEMALE',
      source_module: isER ? 'EMERGENCY' : 'ADMISSION',
      ward_name: isER ? 'Emergency Department (ER)' : 'MEDICAL WARD (WARD 4)',
      room_bed: isER ? 'ER Triage / Bay' : 'TEMB1',
      admitting_diagnosis: isER ? 'ACUTE EMERGENCY ENCOUNTER • CPH BALAMBAN' : 'ACUTE MEDICAL ENCOUNTER • CPH BALAMBAN',
      accommodation: 'SERVICE',
      type_of_service: isER ? 'SURGICAL' : 'MEDICAL',
      attending_physician: 'CPH Balamban Attending Physician',
      admission_date: '08/29/2026',
      admission_time: '12:40 PM',
      code_status: 'FULL_CODE',
      allergies: ['NKDA'],
      blood_type: 'O+',
      fall_risk: 'MEDIUM',
      ihomis_url: isER ? `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-${normalized}` : `${IHOMIS_CONFIG.admissionUrl}?hrn=${raw}`,
    };
  }

  public static getPatientsByModule(module?: IHOMISSourceModule): IHOMISPatient[] {
    if (!module) return MOCK_IHOMIS_PATIENTS;
    return MOCK_IHOMIS_PATIENTS.filter(p => p.source_module === module);
  }
}
