import { IHOMISPatient, IHOMISConfig, IHOMISSourceModule, IHOMISMetrics } from '@/types/ihomis';

export const IHOMIS_CONFIG: IHOMISConfig = {
  baseUrl: process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local',
  admissionUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Admission`,
  emergencyUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Emergency/index`,
  outpatientUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Outpatient`,
  personnelUrl: `${process.env.NEXT_PUBLIC_IHOMIS_URL || 'https://ihomis-plus.cphb.local'}/Ref_Personnel`,
  hospitalName: 'Cebu Provincial Hospital - Balamban (CPHB)',
  isLiveConnected: true,
};

// Exact Live Encounter Metrics from CPH Balamban iHOMIS Plus System
export const IHOMIS_LIVE_METRICS: IHOMISMetrics = {
  activeAdmissions: 172,
  admissionsMale: 75,
  admissionsFemale: 97,
  longStayCount: 55,
  erEncounters: 294,
  erMale: 4,
  erFemale: 11,
  erForAdmission: 0,
};

// Full patient dataset matching all CPH Balamban screenshots (Inpatient, Outpatient, Emergency)
export const MOCK_IHOMIS_PATIENTS: IHOMISPatient[] = [
  // ==========================================
  // 1. INPATIENT ADMISSIONS (/Admission)
  // ==========================================
  {
    hrn: '000000000025909',
    case_no: 'ADM-2026-0025909',
    patient_name: 'NIEZ, MELANIE, CUESTA',
    age: 33,
    dob: '10/14/1992',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 5 (OB-GYN)',
    room_bed: 'OBNEWROOM',
    admitting_diagnosis: 'G3P2 (2002) PU 32 1/7 WEEKS AOG PRETERM IN LABOR; PROM X 9 HOURS',
    chief_complaint: 'Preterm labor contractions, ruptured membranes',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'OB-GYN Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '01:30 PM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000025909`,
  },
  {
    hrn: '000000000157233',
    case_no: 'ADM-2026-157233',
    patient_name: 'SEGUROS, GINIVIEVE, PIS-AN',
    age: 31,
    dob: '11/01/1995',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 5 (OB-GYN)',
    room_bed: 'tempobed-ward05A',
    admitting_diagnosis: 'G2P1 (1001) PU 38 5/7 WEEKS AOG CEPHALIC IN LABOR',
    chief_complaint: 'Active labor contractions',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBPRDOC',
    attending_physician: 'OB-GYN Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '11:30 AM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157233`,
  },
  {
    hrn: '000000000157210',
    case_no: 'ADM-2026-157210',
    patient_name: 'LEGASPINO, EDELYN, CABRAS',
    age: 27,
    dob: '11/19/1998',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 5 (OB-GYN)',
    room_bed: 'tempobed-ward05B',
    admitting_diagnosis: 'G1P0 PREGNANCY UTERINE FULLTERM CEPHALIC IN LABOR',
    chief_complaint: 'Full term active labor',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBPRDOC',
    attending_physician: 'OB-GYN Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '11:00 AM',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'B+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157210`,
  },
  {
    hrn: '000000000084045',
    case_no: 'ADM-2026-084045',
    patient_name: 'CARIAS, JENNIFER, SIAROT',
    age: 32,
    dob: '08/09/1994',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'WARD 5 (OB-GYN)',
    room_bed: 'tempobed-ward05C',
    admitting_diagnosis: 'G2P1 (1001) PU 38 3/7 WEEKS AOG PREVIOUS CS X 1 (2022) CPH BALAMBAN',
    chief_complaint: 'Previous CS scar tenderness in labor',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'OB-GYN Attending Physician',
    admission_date: '08/29/2026',
    admission_time: '09:00 AM',
    code_status: 'FULL_CODE',
    allergies: ['Penicillin'],
    blood_type: 'A+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000084045`,
  },
  {
    hrn: '000000000157208',
    case_no: 'ADM-2026-157208',
    patient_name: 'CASTILLON, BB. GIRL (CRISTEL)',
    age: 0,
    dob: '08/29/2026',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'ICU NEW ROOM (NICU)',
    room_bed: 'TEMPBED4-ICU4',
    admitting_diagnosis: 'A LIVE TERM FEMALE NEONATE DELIVERED CEPHALIC VIA NSD AS 8,9 BS 39 WEEKS BW 2.95 KGS AGA',
    chief_complaint: 'Newborn monitoring & immediate neonatal care',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Pediatric Specialist',
    admission_date: '08/29/2026',
    admission_time: '06:27 AM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157208`,
  },
  {
    hrn: '000000000157206',
    case_no: 'ADM-2026-157206',
    patient_name: 'ENGRESO, BABY GIRL (LEA)',
    age: 0,
    dob: '08/29/2026',
    gender: 'FEMALE',
    source_module: 'ADMISSION',
    ward_name: 'ICU NEW ROOM (NICU)',
    room_bed: 'TEMPBED5-ICU5',
    admitting_diagnosis: 'A LIVE TERM FEMALE NEONATE DELIVERED CEPHALIC VIA NSD AS 8,9 BS 41 WEEKS, BW 3500 GRAMS AGA',
    chief_complaint: 'Neonatal observation & routine vaccination',
    accommodation: 'NON-BASIC',
    type_of_service: 'OBNEWROOM',
    attending_physician: 'Pediatric Specialist',
    admission_date: '08/29/2026',
    admission_time: '06:04 AM',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000157206`,
  },
  {
    hrn: '000000000141843',
    case_no: 'ADM-2026-00141843',
    patient_name: 'ESTINOR, SOFRONIO JR., GERA',
    age: 76,
    dob: '05/24/1950',
    gender: 'MALE',
    source_module: 'ADMISSION',
    ward_name: 'MEDICAL WARD (WARD 4)',
    room_bed: 'TEMB4',
    admitting_diagnosis: 'LUNG CA STAGE IV WITH BONE METASTASIS',
    chief_complaint: 'Intractable bone pain, hemoptysis, chronic cough',
    accommodation: 'NON-BASIC',
    type_of_service: 'MEDICAL',
    attending_physician: 'Internal Medicine Attending',
    admission_date: '02/12/2026',
    admission_time: '12:50 AM',
    code_status: 'FULL_CODE',
    allergies: ['Morphine sensitivity', 'Tramadol'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000141843`,
  },
  {
    hrn: '000000000147689',
    case_no: 'ADM-2026-00147689',
    patient_name: 'MONTECILLO, REYNALDO, BACLAYON',
    age: 64,
    dob: '03/15/1962',
    gender: 'MALE',
    source_module: 'ADMISSION',
    ward_name: 'ICU NEW ROOM',
    room_bed: 'ICU01',
    admitting_diagnosis: 'ACUTE CORONARY SYNDROME - NSTEMI; DM TYPE 2',
    chief_complaint: 'Substernal chest tightness radiating to left arm',
    accommodation: 'NON-BASIC',
    type_of_service: 'ICU',
    attending_physician: 'Cardiologist on Duty',
    admission_date: '08/25/2026',
    admission_time: '03:15 PM',
    code_status: 'FULL_CODE',
    allergies: ['Aspirin (Mild Gastritis)'],
    blood_type: 'AB+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.admissionUrl}?hrn=000000000147689`,
  },

  // ==========================================
  // 2. OUTPATIENT LISTS (/Outpatient)
  // ==========================================
  {
    hrn: '000000000106498',
    case_no: 'OPD-2026-00106498',
    patient_name: 'MELANO, CHRIZEL, ANTIMARO',
    age: 8,
    dob: '04/10/2018',
    gender: 'FEMALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Outpatient Department (OPD)',
    room_bed: 'PEDIATRICS CLINIC',
    admitting_diagnosis: 'PEDIATRIC UPPER RESPIRATORY TRACT INFECTION',
    chief_complaint: 'Fever x 3 days, non-productive cough',
    accommodation: 'SERVICE',
    type_of_service: 'PEDIATRICS',
    attending_physician: 'OPD Pediatrician',
    admission_date: '08/29/2026',
    admission_time: '12:55 PM',
    disposition: 'TREATED & OUTPATIENT RX',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'LOW',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000106498`,
  },
  {
    hrn: '000000000013092',
    case_no: 'OPD-2026-00013092',
    patient_name: 'NAVARRO, EMMA, DELA CERNA',
    age: 58,
    dob: '02/14/1968',
    gender: 'FEMALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Hemodialysis Unit',
    room_bed: 'DIALYSIS STATION 01',
    admitting_diagnosis: 'END-STAGE RENAL DISEASE ON REGULAR MAINTENANCE HEMODIALYSIS',
    chief_complaint: 'Routine hemodialysis clearance',
    accommodation: 'SERVICE',
    type_of_service: 'HEMODIALYSIS',
    attending_physician: 'Nephrologist Attending',
    admission_date: '08/29/2026',
    admission_time: '12:03 PM',
    disposition: 'HEMODIALYSIS IN PROGRESS',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'A+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000013092`,
  },
  {
    hrn: '000000000046909',
    case_no: 'OPD-2026-00046909',
    patient_name: 'PABROA, CHERIE, ESPINOSA',
    age: 49,
    dob: '07/21/1977',
    gender: 'FEMALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Hemodialysis Unit',
    room_bed: 'DIALYSIS STATION 02',
    admitting_diagnosis: 'CHRONIC KIDNEY DISEASE STAGE 5 ON MAINTENANCE HD',
    chief_complaint: 'Scheduled 4-hour hemodialysis run',
    accommodation: 'SERVICE',
    type_of_service: 'HEMODIALYSIS',
    attending_physician: 'Nephrologist Attending',
    admission_date: '08/29/2026',
    admission_time: '12:00 PM',
    disposition: 'HEMODIALYSIS IN PROGRESS',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000046909`,
  },
  {
    hrn: '000000000146331',
    case_no: 'OPD-2026-00146331',
    patient_name: 'OY, BIENVENIDO, ALCOMENDRES',
    age: 62,
    dob: '09/05/1963',
    gender: 'MALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Hemodialysis Unit',
    room_bed: 'DIALYSIS STATION 03',
    admitting_diagnosis: 'HYPERTENSIVE NEPHROSCLEROSIS • MAINTENANCE HD',
    chief_complaint: 'Bi-weekly hemodialysis session',
    accommodation: 'SERVICE',
    type_of_service: 'HEMODIALYSIS',
    attending_physician: 'Nephrologist Attending',
    admission_date: '08/29/2026',
    admission_time: '11:53 AM',
    disposition: 'HEMODIALYSIS IN PROGRESS',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'B+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000146331`,
  },
  {
    hrn: '000000000143134',
    case_no: 'OPD-2026-00143134',
    patient_name: 'CARMELOTES, ROLAND, QUOTIJO',
    age: 55,
    dob: '12/11/1970',
    gender: 'MALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Hemodialysis Unit',
    room_bed: 'DIALYSIS STATION 04',
    admitting_diagnosis: 'DIABETIC NEPHROPATHY • ESRD HEMODIALYSIS',
    chief_complaint: 'Fluid overload, routine HD session',
    accommodation: 'SERVICE',
    type_of_service: 'HEMODIALYSIS',
    attending_physician: 'Nephrologist Attending',
    admission_date: '08/29/2026',
    admission_time: '11:48 AM',
    disposition: 'HEMODIALYSIS IN PROGRESS',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000143134`,
  },
  {
    hrn: '000000000155720',
    case_no: 'OPD-2026-00155720',
    patient_name: 'JAVA, ROSELO, REGODON',
    age: 67,
    dob: '01/30/1959',
    gender: 'MALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Hemodialysis Unit',
    room_bed: 'DIALYSIS STATION 05',
    admitting_diagnosis: 'ESRD ON MAINTENANCE HEMODIALYSIS',
    chief_complaint: 'Routine dialysis session',
    accommodation: 'SERVICE',
    type_of_service: 'HEMODIALYSIS',
    attending_physician: 'Nephrologist Attending',
    admission_date: '08/29/2026',
    admission_time: '11:47 AM',
    disposition: 'HEMODIALYSIS IN PROGRESS',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'AB+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000155720`,
  },
  {
    hrn: '000000000128043',
    case_no: 'OPD-2026-00128043',
    patient_name: 'ALPARA, JANETTE, COLONGAN',
    age: 44,
    dob: '06/18/1982',
    gender: 'FEMALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Hemodialysis Unit',
    room_bed: 'DIALYSIS STATION 06',
    admitting_diagnosis: 'CHRONIC GLOMERULONEPHRITIS • HEMODIALYSIS',
    chief_complaint: 'Scheduled dialysis session',
    accommodation: 'SERVICE',
    type_of_service: 'HEMODIALYSIS',
    attending_physician: 'Nephrologist Attending',
    admission_date: '08/29/2026',
    admission_time: '11:45 AM',
    disposition: 'HEMODIALYSIS IN PROGRESS',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'A+',
    fall_risk: 'LOW',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000128043`,
  },
  {
    hrn: '000000000129365',
    case_no: 'OPD-2026-00129365',
    patient_name: 'NERVAS, CENDIE, SABALANDE',
    age: 39,
    dob: '03/04/1987',
    gender: 'FEMALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Hemodialysis Unit',
    room_bed: 'DIALYSIS STATION 07',
    admitting_diagnosis: 'ESRD ON MAINTENANCE HEMODIALYSIS',
    chief_complaint: 'Maintenance HD',
    accommodation: 'SERVICE',
    type_of_service: 'HEMODIALYSIS',
    attending_physician: 'Nephrologist Attending',
    admission_date: '08/29/2026',
    admission_time: '11:43 AM',
    disposition: 'HEMODIALYSIS IN PROGRESS',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'LOW',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000129365`,
  },
  {
    hrn: '000000000079080',
    case_no: 'OPD-2026-00079080',
    patient_name: 'COMPACION, FORTUNATA, BORGONIA',
    age: 71,
    dob: '10/29/1954',
    gender: 'FEMALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Hemodialysis Unit',
    room_bed: 'DIALYSIS STATION 08',
    admitting_diagnosis: 'ESRD ON MAINTENANCE HEMODIALYSIS',
    chief_complaint: 'Routine dialysis session',
    accommodation: 'SERVICE',
    type_of_service: 'HEMODIALYSIS',
    attending_physician: 'Nephrologist Attending',
    admission_date: '08/29/2026',
    admission_time: '11:41 AM',
    disposition: 'HEMODIALYSIS IN PROGRESS',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000079080`,
  },
  {
    hrn: '000000000019910',
    case_no: 'OPD-2026-00019910',
    patient_name: 'OLAN-OLAN, VERNA, QUENIO',
    age: 46,
    dob: '08/12/1980',
    gender: 'FEMALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Hemodialysis Unit',
    room_bed: 'DIALYSIS STATION 09',
    admitting_diagnosis: 'CKD 5 ON MAINTENANCE HEMODIALYSIS',
    chief_complaint: 'Regular dialysis session',
    accommodation: 'SERVICE',
    type_of_service: 'HEMODIALYSIS',
    attending_physician: 'Nephrologist Attending',
    admission_date: '08/29/2026',
    admission_time: '11:30 AM',
    disposition: 'HEMODIALYSIS IN PROGRESS',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'A+',
    fall_risk: 'LOW',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000019910`,
  },
  {
    hrn: '000000000147107',
    case_no: 'OPD-2026-00147107',
    patient_name: 'PARDILLO, ANGELES, BOBILLES',
    age: 60,
    dob: '05/01/1966',
    gender: 'FEMALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Hemodialysis Unit',
    room_bed: 'DIALYSIS STATION 10',
    admitting_diagnosis: 'ESRD ON MAINTENANCE HEMODIALYSIS',
    chief_complaint: 'Routine dialysis session',
    accommodation: 'SERVICE',
    type_of_service: 'HEMODIALYSIS',
    attending_physician: 'Nephrologist Attending',
    admission_date: '08/29/2026',
    admission_time: '11:05 AM',
    disposition: 'HEMODIALYSIS IN PROGRESS',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'B+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000147107`,
  },
  {
    hrn: '000000000128102',
    case_no: 'OPD-2026-00128102',
    patient_name: 'ROPEROS, RHEA MARIE, ARIAS',
    age: 41,
    dob: '11/03/1984',
    gender: 'FEMALE',
    source_module: 'OUTPATIENT',
    ward_name: 'Hemodialysis Unit',
    room_bed: 'DIALYSIS STATION 11',
    admitting_diagnosis: 'ESRD ON MAINTENANCE HEMODIALYSIS',
    chief_complaint: 'Dialysis clearance and ultrafiltration',
    accommodation: 'SERVICE',
    type_of_service: 'HEMODIALYSIS',
    attending_physician: 'Nephrologist Attending',
    admission_date: '08/29/2026',
    admission_time: '10:30 AM',
    disposition: 'HEMODIALYSIS IN PROGRESS',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'LOW',
    ihomis_url: `${IHOMIS_CONFIG.outpatientUrl}?hrn=000000000128102`,
  },

  // ==========================================
  // 3. EMERGENCY DEPARTMENT (/Emergency)
  // ==========================================
  {
    hrn: '000000000148651',
    case_no: 'ER-2026-00148651',
    patient_name: 'MACAVINTA, BLESSYN ANYA, OLACO',
    age: 5,
    dob: '03/15/2021',
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Pedia Bay 01',
    admitting_diagnosis: 'ACUTE PEDIATRIC EMERGENCY ENCOUNTER',
    chief_complaint: 'Pediatric acute fever and cough evaluation',
    accommodation: 'SERVICE',
    type_of_service: 'PEDIATRICS',
    attending_physician: 'ER Pediatrician on Duty',
    admission_date: '08/29/2026',
    admission_time: '02:30 PM',
    disposition: 'ACUTE PEDIATRIC EVALUATION',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00148651`,
  },
  {
    hrn: '000000000157236',
    case_no: 'ER-2026-00157236',
    patient_name: 'NENGASCA, MARIM',
    age: 28,
    dob: '05/14/1998',
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER OB Triage Bay',
    admitting_diagnosis: 'ACTIVE OBSTETRIC EMERGENCY ENCOUNTER',
    chief_complaint: 'Severe pelvic cramping, vaginal spotting',
    accommodation: 'SERVICE',
    type_of_service: 'OBSTETRICS',
    attending_physician: 'ER Resident on Duty',
    admission_date: '08/29/2026',
    admission_time: '02:20 PM',
    disposition: 'UNDER EVALUATION',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157236`,
  },
  {
    hrn: '000000000157235',
    case_no: 'ER-2026-00157235',
    patient_name: 'AROG, CHARNIE, SIAROT',
    age: 20,
    dob: '07/19/2006',
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Bed 01',
    admitting_diagnosis: 'ACUTE SEVERE DYSPNEA • HYPOXEMIA',
    chief_complaint: 'Sudden shortness of breath, chest heaviness',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'ER Medical Specialist',
    admission_date: '08/29/2026',
    admission_time: '12:19 PM',
    disposition: 'ACUTE EMERGENCY STABILIZATION',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'A+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157235`,
  },
  {
    hrn: '000000000107451',
    case_no: 'ER-2026-00107451',
    patient_name: 'DURAN, JAMES KHIAN, CAPULE',
    age: 19,
    dob: '02/10/2007',
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Trauma Bay 01',
    admitting_diagnosis: 'ACUTE MULTIPLE BLUNT TRAUMA • MOTORCYCLE ACCIDENT',
    chief_complaint: 'Head laceration, right extremity trauma',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'ER Trauma Surgeon',
    admission_date: '08/29/2026',
    admission_time: '11:58 AM',
    disposition: 'SURGICAL EVALUATION',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00107451`,
  },
  {
    hrn: '000000000057010',
    case_no: 'ER-2026-00057010',
    patient_name: 'CASAJURAS, BEA ZHAVIA, PAUL',
    age: 24,
    dob: '11/25/2001',
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Bed 02',
    admitting_diagnosis: 'ACUTE SURGICAL ABDOMEN • SUSPECTED APPENDICITIS',
    chief_complaint: 'RLQ abdominal rebound tenderness',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'ER Surgeon on Duty',
    admission_date: '08/29/2026',
    admission_time: '11:40 AM',
    disposition: 'FOR SURGICAL ADMISSION',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'B+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00057010`,
  },
  {
    hrn: '000000000139643',
    case_no: 'ER-2026-00139643',
    patient_name: 'TOLERO, THALIA ALEXANDRA, BARRICA',
    age: 6,
    dob: '03/12/2020',
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Pedia Bay 01',
    admitting_diagnosis: 'COMPLEX FEBRILE CONVULSIONS • HIGH GRADE FEVER',
    chief_complaint: 'Seizure episode lasting 2 minutes, T 39.4C',
    accommodation: 'SERVICE',
    type_of_service: 'PEDIATRICS',
    attending_physician: 'ER Pediatrician',
    admission_date: '08/29/2026',
    admission_time: '11:20 AM',
    disposition: 'PEDIATRIC OBSERVATION',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00139643`,
  },
  {
    hrn: '000000000030326',
    case_no: 'ER-2026-00030326',
    patient_name: 'OBESO, JAN REY, BENITEZ',
    age: 48,
    dob: '08/17/1978',
    gender: 'MALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Bed 03',
    admitting_diagnosis: 'HYPERTENSIVE URGENCY • BP 210/120 MMHG',
    chief_complaint: 'Severe occipital headache, dizziness',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'ER Medical Specialist',
    admission_date: '08/29/2026',
    admission_time: '11:18 AM',
    disposition: 'BP LOWERING PROTOCOL',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00030326`,
  },
  {
    hrn: '000000000082895',
    case_no: 'ER-2026-00082895',
    patient_name: 'CHAVOSO, KALEB MAXIMILLIAN, CLIMACO',
    age: 15,
    dob: '09/02/2010',
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Trauma Bay 02',
    admitting_diagnosis: 'CLOSED FOREARM FRACTURE • ACCIDENTAL FALL',
    chief_complaint: 'Deformed left distal radius, severe pain',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'Orthopedic Consultant',
    admission_date: '08/29/2026',
    admission_time: '11:02 AM',
    disposition: 'FOR CLOSED REDUCTION & CASTING',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'A+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00082895`,
  },
  {
    hrn: '000000000157229',
    case_no: 'ER-2026-00157229',
    patient_name: 'DINOY, MARIA FLOR, ROSALES',
    age: 52,
    dob: '10/08/1973',
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Bed 04',
    admitting_diagnosis: 'COMMUNITY ACQUIRED PNEUMONIA - MODERATE RISK',
    chief_complaint: 'Productive cough, chest wall pain, T 38.6C',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'ER Medical Specialist',
    admission_date: '08/29/2026',
    admission_time: '10:41 AM',
    disposition: 'FOR ADMISSION TO MEDICAL WARD',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157229`,
  },
  {
    hrn: '000000000157227',
    case_no: 'ER-2026-00157227',
    patient_name: 'CAMUS, NINA, TINGAL',
    age: 26,
    dob: '12/03/1999',
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Bed 05',
    admitting_diagnosis: 'ACUTE GASTROENTERITIS WITH MODERATE DEHYDRATION',
    chief_complaint: 'Watery diarrhea x 8 episodes, vomiting',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'ER Resident on Duty',
    admission_date: '08/29/2026',
    admission_time: '10:33 AM',
    disposition: 'IV FLUID REHYDRATION',
    code_status: 'FULL_CODE',
    allergies: ['None'],
    blood_type: 'O+',
    fall_risk: 'LOW',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157227`,
  },
  {
    hrn: '000000000157228',
    case_no: 'ER-2026-00157228',
    patient_name: 'DADO, CORINNE TRECIA, SABULAO',
    age: 35,
    dob: '04/16/1991',
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Bed 06',
    admitting_diagnosis: 'ACUTE EXACERBATION OF BRONCHIAL ASTHMA',
    chief_complaint: 'Wheezing, chest tightness, tachypnea',
    accommodation: 'SERVICE',
    type_of_service: 'MEDICAL',
    attending_physician: 'ER Medical Specialist',
    admission_date: '08/29/2026',
    admission_time: '10:32 AM',
    disposition: 'NEBULIZATION THERAPY',
    code_status: 'FULL_CODE',
    allergies: ['Aspirin'],
    blood_type: 'B+',
    fall_risk: 'LOW',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157228`,
  },
  {
    hrn: '000000000157230',
    case_no: 'ER-2026-00157230',
    patient_name: 'SANDE, ZAFIRA QUINN, RICABORDA',
    age: 18,
    dob: '01/22/2008',
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Trauma Bay 03',
    admitting_diagnosis: 'ACUTE ANKLE LIGAMENTOUS INJURY / SPRAIN',
    chief_complaint: 'Ankle inversion injury with severe swelling',
    accommodation: 'SERVICE',
    type_of_service: 'SURGICAL',
    attending_physician: 'ER Surgeon on Duty',
    admission_date: '08/29/2026',
    admission_time: '10:26 AM',
    disposition: 'SPLINTING & ORTHOPEDIC FOLLOW UP',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'MEDIUM',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157230`,
  },
  {
    hrn: '000000000157225',
    case_no: 'ER-2026-00157225',
    patient_name: 'VILLA, ARLYN JANE, BASALO',
    age: 4,
    dob: '08/04/2022',
    gender: 'FEMALE',
    source_module: 'EMERGENCY',
    ward_name: 'Emergency Department (ER)',
    room_bed: 'ER Pedia Bay 02',
    admitting_diagnosis: 'ACUTE BRONCHIOLITIS • MILD RESPIRATORY DISTRESS',
    chief_complaint: 'Cough, subcostal retractions, fever',
    accommodation: 'SERVICE',
    type_of_service: 'PEDIATRICS',
    attending_physician: 'ER Pediatrician',
    admission_date: '08/29/2026',
    admission_time: '10:25 AM',
    disposition: 'PEDIATRIC OBSERVATION & O2 THERAPY',
    code_status: 'FULL_CODE',
    allergies: ['NKDA'],
    blood_type: 'O+',
    fall_risk: 'HIGH',
    ihomis_url: `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-00157225`,
  },
];

const LOCAL_STORAGE_KEY_PATIENTS = 'ihomis_patients_live_v1';

export class IHOMISService {
  private static livePatients: IHOMISPatient[] = [...MOCK_IHOMIS_PATIENTS];
  private static isCloudSyncInitialized = false;

  public static getMetrics(): IHOMISMetrics {
    const activeAdmissions = this.getPatientsByModule('ADMISSION').length;
    const erEncounters = this.getPatientsByModule('EMERGENCY').length;
    return {
      activeAdmissions: activeAdmissions > 50 ? activeAdmissions : IHOMIS_LIVE_METRICS.activeAdmissions,
      admissionsMale: IHOMIS_LIVE_METRICS.admissionsMale,
      admissionsFemale: IHOMIS_LIVE_METRICS.admissionsFemale,
      longStayCount: IHOMIS_LIVE_METRICS.longStayCount,
      erEncounters: erEncounters > 50 ? erEncounters : IHOMIS_LIVE_METRICS.erEncounters,
      erMale: IHOMIS_LIVE_METRICS.erMale,
      erFemale: IHOMIS_LIVE_METRICS.erFemale,
      erForAdmission: IHOMIS_LIVE_METRICS.erForAdmission,
    };
  }

  public static initCloudSync() {
    if (typeof window === 'undefined') return;
    if (this.isCloudSyncInitialized) return;
    this.isCloudSyncInitialized = true;

    // 1. Read from localStorage if available
    try {
      const raw = localStorage.getItem(LOCAL_STORAGE_KEY_PATIENTS);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed) && parsed.length > 0) {
          this.livePatients = parsed;
        }
      }
    } catch (e) {
      console.warn('Error reading local patients:', e);
    }

    // 2. Fetch latest from Cloud
    this.fetchPatientsFromCloud();
  }

  public static async fetchPatientsFromCloud(): Promise<IHOMISPatient[]> {
    try {
      const res = await fetch('/api/ihomis/patients', { cache: 'no-store' });
      if (res.ok) {
        const json = await res.json();
        if (json.success && Array.isArray(json.patients) && json.patients.length > 0) {
          this.livePatients = json.patients;
          if (typeof window !== 'undefined') {
            try {
              localStorage.setItem(LOCAL_STORAGE_KEY_PATIENTS, JSON.stringify(json.patients));
            } catch (e) {}
          }
          return json.patients;
        }
      }
    } catch (e) {
      console.warn('Cloud patient fetch error:', e);
    }
    return this.livePatients;
  }

  public static async savePatientsToCloud(patients: IHOMISPatient[]): Promise<boolean> {
    this.livePatients = patients;
    if (typeof window !== 'undefined') {
      try {
        localStorage.setItem(LOCAL_STORAGE_KEY_PATIENTS, JSON.stringify(patients));
      } catch (e) {}
    }

    try {
      const res = await fetch('/api/ihomis/patients', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ patients }),
      });
      return res.ok;
    } catch (e) {
      console.warn('Save patients to cloud error:', e);
      return false;
    }
  }

  private static normalizeQuery(q: string): string {
    return q.trim().toLowerCase().replace(/^0+/, '');
  }

  public static getAllPatients(): IHOMISPatient[] {
    return this.livePatients;
  }

  public static findPatientByLocation(locationText: string): IHOMISPatient | null {
    if (!locationText) return null;
    const cleanQuery = locationText.toLowerCase();

    const exact = this.livePatients.find(p => 
      cleanQuery.includes(p.room_bed.toLowerCase()) ||
      (cleanQuery.includes(p.ward_name.toLowerCase()) && cleanQuery.includes(p.room_bed.toLowerCase()))
    );
    if (exact) return exact;

    const partial = this.livePatients.find(p => {
      const bedPart = p.room_bed.toLowerCase().replace(/[^a-z0-9]/g, '');
      const queryPart = cleanQuery.replace(/[^a-z0-9]/g, '');
      if (bedPart && queryPart.includes(bedPart)) return true;
      if (cleanQuery.includes('er') && p.source_module === 'EMERGENCY') return true;
      if (cleanQuery.includes('temb4') && p.room_bed.toLowerCase().includes('temb4')) return true;
      if (cleanQuery.includes('temb1') && p.room_bed.toLowerCase().includes('temb1')) return true;
      return false;
    });

    return partial || null;
  }

  public static findPatientByHRN(hrnOrCase: string, preferredModule?: IHOMISSourceModule): IHOMISPatient | null {
    if (!hrnOrCase) return null;
    const raw = hrnOrCase.trim().toLowerCase();
    const normalized = this.normalizeQuery(hrnOrCase);

    const match = this.livePatients.find(p => {
      const pHrn = p.hrn.toLowerCase();
      const pNormHrn = this.normalizeQuery(p.hrn);
      const pCase = p.case_no.toLowerCase();
      const pName = p.patient_name.toLowerCase();

      return (
        pHrn.includes(raw) ||
        pNormHrn.includes(normalized) ||
        pCase.includes(raw) ||
        pName.includes(raw)
      );
    });

    if (match) return match;

    const isER = preferredModule === 'EMERGENCY' || raw.includes('er');
    return {
      hrn: raw.padStart(15, '0'),
      case_no: isER ? `ER-2026-${normalized}` : `ADM-2026-${normalized}`,
      patient_name: `PATIENT RECORD (HRN ${raw})`,
      age: 35,
      dob: '01/01/1990',
      gender: 'FEMALE',
      source_module: isER ? 'EMERGENCY' : (preferredModule === 'OUTPATIENT' ? 'OUTPATIENT' : 'ADMISSION'),
      ward_name: isER ? 'Emergency Department (ER)' : (preferredModule === 'OUTPATIENT' ? 'Outpatient Department (OPD)' : 'MEDICAL WARD (WARD 4)'),
      room_bed: isER ? 'ER Triage / Bay' : (preferredModule === 'OUTPATIENT' ? 'OPD Clinic' : 'TEMB1'),
      admitting_diagnosis: isER ? 'ACUTE EMERGENCY ENCOUNTER • CPH BALAMBAN' : 'CLINICAL ENCOUNTER • CPH BALAMBAN',
      accommodation: 'SERVICE',
      type_of_service: isER ? 'SURGICAL' : 'MEDICAL',
      attending_physician: 'CPH Balamban Attending Physician',
      admission_date: '08/29/2026',
      admission_time: '12:40 PM',
      code_status: 'FULL_CODE',
      allergies: ['NKDA'],
      blood_type: 'O+',
      fall_risk: 'MEDIUM',
      ihomis_url: isER ? `${IHOMIS_CONFIG.emergencyUrl}?case=ER-2026-${normalized}` : `${IHOMIS_CONFIG.admissionUrl}?hrn=${raw}`,
    };
  }

  public static getPatientsByModule(module?: IHOMISSourceModule): IHOMISPatient[] {
    if (!module) return this.livePatients;
    return this.livePatients.filter(p => p.source_module === module);
  }
}
